# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "archlinux/archlinux"
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network", bridge: "wlan0"


  config.vm.synced_folder ".", "/vagrant_data"


  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    id

    pacman -Syu --noconfirm --needed \
      linux-headers \
      git \
      make gcc pkg-config ncurses flex bison bc cpio\
      strace 
    
    mkdir -p linux
    git clone --depth=1 git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git  /vagrant_data/linux

    # strace -o ../strace_make.log -T -ttt -f -- make -j4
    echo "TERM=linux" >> /etc/profile
  SHELL
end
